### ISSUE TITLE
 Unsupported formats

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/view-and-data-npm#5]
like .VRML, .max

**Comment by shiya** [comment]
It's not something this npm package is aiming to solve.

**Comment by cyrillef** [comment]
To be  a bit more specific, what Shiya is saying is that the NPM package here wraps a REST API, and doe snot care about file format. The WEB service behind the API does handle many file formats, see below. .max and .vrml are not yet supported. While I am sure .max will be soon, I am less certain for .vrml since it is an old format that none of the VR actors today are using. In the meantime for .max, you can use the FBX SDK to translate to obj or fbx.

"extensions": [
    "ipt",
    "neu",
    "stla",
    "stl",
    "jt",
    "skp",
    "collaboration",
    "prt",
    "dwf",
    "sldasm",
    "step",
    "dwg",
    "zip",
    "nwc",
    "model",
    "stp",
    "ste",
    "f3d",
    "dgn",
    "pdf",
    "iges",
    "idw",
    "dwt",
    "dxf",
    "catproduct",
    "igs",
    "sldprt",
    "cgr",
    "3dm",
    "sab",
    "obj",
    "cam360",
    "gbxml",
    "exp",
    "wire",
    "ige",
    "rcp",
    "dae",
    "x_b",
    "3ds",
    "rvt",
    "g",
    "iam",
    "asm",
    "dlv3",
    "x_t",
    "session",
    "xas",
    "xpr",
    "catpart",
    "stlb",
    "nwd",
    "sat",
    "fbx",
    "smb",
    "smt",
    "ifc",
    "dwfx",
    "xlsx",
    "jpg",
    "xls",
    "png",
    "csv",
    "pptx",
    "jpeg",
    "bmp",
    "ppt",
    "doc",
    "txt",
    "rtf",
    "pps",
    "docx",
    "tiff",
    "tif",
    "simstudy"
  ]
